import type { Metadata } from "next";
import "./globals.css";
import { jost } from "./ui/fonts";
import Sidebar from "./ui/sidebar";
import ClientProvider from "./store/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className}  antialiased`}>
        {" "}
        <ClientProvider>
          <Sidebar />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
